Updated all the scriptz - Too many changes to list!

diff --git a/scripts/file-downloaded-hook b/scripts/file-downloaded-hook
--- a/scripts/file-downloaded-hook
+++ b/scripts/file-downloaded-hook
@@ -1,41 +1,58 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-AMQP_SCRIPT="/usr/bin/send-amqp-message"
-GDRIVE_SCRIPT="/usr/bin/upload-google-drive"
-LDB="/usr/local/bin/ldb"
-LEVELDB_DB="/data/filesdb"
+# global parameters
+set -o pipefail # prevents errors in a pipeline from being masked
+
+FILE_DOWNLOADED_HOOK_LOG=${FILE_DOWNLOADED_HOOK_LOG:="/var/log/file-downloaded.log"}
+
+# Import the BLOG library
+[ -f "$BLOG" ] && source "$BLOG" || { echo "I require b-log.sh but it's not found.  Aborting."; exit 1; }
+# Here we are matching the BLOG format to match the format of rclone
+B_LOG_DEFAULT_TEMPLATE="@19:1@ @5:2@ : @5@"
+LOG_LEVELS=(
+    ${LOG_LEVEL_FATAL}  "FATAL"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[41;37m" "\e[0m"
+    ${LOG_LEVEL_ERROR}  "ERROR"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;31m" "\e[0m"
+    ${LOG_LEVEL_WARN}   "WARN"   "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;33m" "\e[0m"
+    ${LOG_LEVEL_NOTICE} "NOTICE" "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;32m" "\e[0m"
+    ${LOG_LEVEL_INFO}   "INFO"   "${B_LOG_DEFAULT_TEMPLATE}" "\e[37m" "\e[0m"
+    ${LOG_LEVEL_DEBUG}  "DEBUG"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;34m" "\e[0m"
+    ${LOG_LEVEL_TRACE}  "TRACE"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[94m" "\e[0m"
+)
+
+# Setup some B-Log variables
+B_LOG --file "$FILE_DOWNLOADED_HOOK_LOG" --stdout true --date-format '%Y/%m/%d %H:%M:%S'
+LOG_LEVEL_ALL
+
 FILENAME="$1"
+
+AMQP_SCRIPT=${AMQP_SCRIPT:-"/usr/bin/send-amqp-message"}
+GDRIVE_SCRIPT=${GDRIVE_SCRIPT:-"/usr/bin/upload-google-drive"}
+LDB=${LDB:-"/usr/local/bin/ldb"}
+LEVELDB_DB=${LEVELDB_DB:-"/data/filesdb"}
 BASE_FILENAME=`dirname "$FILENAME"`
+SHA1_FILEHASH=`sha1sum "$FILENAME" | cut -f1 -d' '`
+
+[ "$FILENAME" != "" ] || { FATAL "Must pass a filename.  Aborting."; exit 1; }
+[ -f "$FILENAME" ] || { FATAL "Filename does not exist '$FILENAME'.  Aborting."; exit 1; }
+
+# Make sure that our LevelDB exists
+[ `"$LDB" "${LEVELDB_DB}" --create --size` ] || { FATAL "Could not create LevelDB '$LEVELDB_DB'.  Aborting."; exit 1; }
+# Check if we have a filesize already for this file
+SAVED_FILESIZE=`"$LDB" "${LEVELDB_DB}" get "$SHA1_FILEHASH" 2>/dev/null`
 FILESIZE=`stat --printf="%s" "$FILENAME"`
 
-if [[ ! -f "$FILENAME" ]]; then
-  echo "File does not exist!"
-  echo "$FILENAME"
-  exit 1
-fi
+# If have a filesize and it matches our current filesize then skip
+[ "$FILESIZE" == "$SAVED_FILESIZE" ] && { NOTICE "File already sent '$BASE_FILENAME'.  Ignoring."; exit 0; }
+NOTICE "New file found: $BASE_FILENAME"
 
-"$LDB" "${LEVELDB_DB}" --create --size
-SAVED_FILESIZE=`"$LDB" "${LEVELDB_DB}" get "$BASE_FILENAME" 2>/dev/null`
-if [[ "$FILESIZE" == "$SAVED_FILESIZE" ]]; then
-  echo "File already sent. Skipping"
-  echo "$BASE_FILENAME"
-  exit 0
-fi
-
-echo "New file found: $FILENAME"
-
-MSG="local|${FILENAME}"
+METADATA=""
 if [[ "${RCLONE_UPLOAD}" == "true" ]]; then
   "$GDRIVE_SCRIPT" "$FILENAME" "$BASE_FILENAME"
-  MSG="google|${BASE_FILENAME}"
-  echo "File uploaded to Google Drive: $BASE_FILENAME"
+  METADATA='type=google_drive'
 fi
 
 if [[ "${AMQP_ENABLED}" == "true" ]]; then
-  #"$AMQP_SCRIPT" "$MSG"
-  echo "$AMQP_SCRIPT" "$MSG"
-  echo "File sent to AMQP queue"
+  "$AMQP_SCRIPT" "$MSG" "$METADATA"
 fi
 
-"$LDB" "${LEVELDB_DB}" put "$BASE_FILENAME" "$FILESIZE"
-echo "File Successfully Processed"
+"$LDB" "${LEVELDB_DB}" put "$SHA1_FILEHASH" "$FILESIZE"
diff --git a/scripts/send-amqp-message b/scripts/send-amqp-message
--- a/scripts/send-amqp-message
+++ b/scripts/send-amqp-message
@@ -1,3 +1,75 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
+# global parameters
+set -o pipefail # prevents errors in a pipeline from being masked
 
+AMQP_PUBLISH_LOG=${AMQP_PUBLISH_LOG:="/var/log/amqp-publish.log"}
+
+# Import the BLOG library
+[ -f "$BLOG" ] && source "$BLOG" || { echo "I require b-log.sh but it's not found.  Aborting."; exit 1; }
+# Here we are matching the BLOG format to match the format of rclone
+B_LOG_DEFAULT_TEMPLATE="@19:1@ @5:2@ : @5@"
+LOG_LEVELS=(
+    ${LOG_LEVEL_FATAL}  "FATAL"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[41;37m" "\e[0m"
+    ${LOG_LEVEL_ERROR}  "ERROR"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;31m" "\e[0m"
+    ${LOG_LEVEL_WARN}   "WARN"   "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;33m" "\e[0m"
+    ${LOG_LEVEL_NOTICE} "NOTICE" "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;32m" "\e[0m"
+    ${LOG_LEVEL_INFO}   "INFO"   "${B_LOG_DEFAULT_TEMPLATE}" "\e[37m" "\e[0m"
+    ${LOG_LEVEL_DEBUG}  "DEBUG"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;34m" "\e[0m"
+    ${LOG_LEVEL_TRACE}  "TRACE"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[94m" "\e[0m"
+)
+
+# Setup some B-Log variables
+B_LOG --file "$AMQP_PUBLISH_LOG" --stdout true --date-format '%Y/%m/%d %H:%M:%S'
+LOG_LEVEL_ALL
+
+# Check if the commands are installed
+command -v "amqp-publish" >/dev/null 2>&1 || { FATAL "I require amqp-publish but it's not installed.  Aborting."; exit 1; }
+
+[ "$AMQP_ENABLED" == "true" ] || { ERROR "AMQP_ENABLED is not equal to true.  Aborting."; exit 1; }
+
+FILENAME="$1"
+METADATA="$2"
+[ "$FILENAME" != "" ] || { FATAL "Must pass a filename.  Aborting."; exit 1; }
+[ -f "$FILENAME" ] || { FATAL "Filename does not exist '$FILENAME'.  Aborting."; exit 1; }
+
+KV_STRING=""
+if [[ "$METADATA" != "" ]]; then
+  for KEY_VALUE in ${METADATA//,/ }; do
+    KEY=`echo "$KEY_VALUE" | cut -f1 -d'='`
+    VALUE=`echo "$KEY_VALUE" | cut -f2 -d'='`
+    KV="\"${KEY}\":\"${VALUE}\""
+    KV_STRING="${KV_STRING},${KV}"
+  done
+fi
+
+BODY_MSG="{\"filename\":\"${FILENAME}\"${KV_STRING}}"
+
+# This is a complicated one liner to extract the host and port from a URL
+AMQP_EXTRACT=`echo "$AMQP_URL" | python -c "import re; s = '${AMQP_URL}'; m = re.search(r'^((?P<scheme>[^:/?#]+):(?=//))?(//)?(((?P<login>[^:]+)(?::(?P<password>[^@]+)?)?@)?(?P<host>[^@/?#:]*)(?::(?P<port>\d+)?)?)?(?P<path>[^?#]*)(\?(?P<query>[^#]*))?(#(?P<fragment>.*))?', s); host = m.group('host') if m.group('host') else ''; port = m.group('port') if m.group('port') else ''; print(host + ':' + port)"`
+AMQP_HOST=`echo "$AMQP_EXTRACT" | cut -f1 -d':'`
+AMQP_PORT=`echo "$AMQP_EXTRACT" | cut -f2 -d':'`
+AMQP_PORT=${AMQP_PORT:-5672}
+AMQP_HOST_PORT_TIMEOUT_SECS=2
+
+# Check if the
+nc -w $AMQP_HOST_PORT_TIMEOUT_SECS "$AMQP_HOST" $AMQP_PORT 2>/dev/null || { FATAL "Looks like AMQP host '$AMQP_HOST:$AMQP_PORT' is not responding.  Aborting."; exit 1; }
+
+# echo "amqp-publish \
+#   --url=\"$AMQP_URL\" \
+#   --exchange=\"$AMQP_EXCHANGE\" \
+#   --routing-key=\"$AMQP_QUEUE\" \
+#   --content-type=\"application/json\" \
+#   --content-encoding=\"utf-8\" \
+#   --heartbeat 1 \
+#   --body=\"${BODY_MSG}\""
+
+amqp-publish \
+  --url="$AMQP_URL" \
+  --exchange="$AMQP_EXCHANGE" \
+  --routing-key="$AMQP_QUEUE" \
+  --content-type="application/json" \
+  --content-encoding="utf-8" \
+  --body="${BODY_MSG}" && \
+NOTICE "Successfully sent AMQP message. Exchange='${AMQP_EXCHANGE}', Routing Key='${AMQP_QUEUE}', Body='${BODY_MSG}'" || \
+ERROR "Failed to send AMQP message!"
diff --git a/scripts/upload-google-drive b/scripts/upload-google-drive
--- a/scripts/upload-google-drive
+++ b/scripts/upload-google-drive
@@ -1,36 +1,87 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-RCLONE_LOCAL="local"
-RCLONE_CONFIG_FILE="/config/rclone.conf"
+# global parameters
+set -o pipefail # prevents errors in a pipeline from being masked
+GOOGLE_DRIVE_UPLOAD_LOG_FILE=${GOOGLE_DRIVE_UPLOAD_LOG_FILE:="/var/log/google-drive-upload.log"}
+
+# Import the BLOG library
+[ -f "$BLOG" ] && source "$BLOG" || { echo "I require b-log.sh but it's not found.  Aborting."; exit 1; }
+# Here we are matching the BLOG format to match the format of rclone
+B_LOG_DEFAULT_TEMPLATE="@19:1@ @5:2@ : @5@"
+LOG_LEVELS=(
+    ${LOG_LEVEL_FATAL}  "FATAL"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[41;37m" "\e[0m"
+    ${LOG_LEVEL_ERROR}  "ERROR"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;31m" "\e[0m"
+    ${LOG_LEVEL_WARN}   "WARN"   "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;33m" "\e[0m"
+    ${LOG_LEVEL_NOTICE} "NOTICE" "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;32m" "\e[0m"
+    ${LOG_LEVEL_INFO}   "INFO"   "${B_LOG_DEFAULT_TEMPLATE}" "\e[37m" "\e[0m"
+    ${LOG_LEVEL_DEBUG}  "DEBUG"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[1;34m" "\e[0m"
+    ${LOG_LEVEL_TRACE}  "TRACE"  "${B_LOG_DEFAULT_TEMPLATE}" "\e[94m" "\e[0m"
+)
+
+# Setup some B-Log variables
+B_LOG --file "$GOOGLE_DRIVE_UPLOAD_LOG_FILE" --stdout true --date-format '%Y/%m/%d %H:%M:%S'
+LOG_LEVEL_ALL
+
+# Check if the commands are installed
+command -v rclone >/dev/null 2>&1 || { FATAL "I require rclone but it's not installed.  Aborting."; exit 1; }
+command -v crudini >/dev/null 2>&1 || { FATAL "I require crudini but it's not installed.  Aborting."; exit 1; }
+
+[ "$RCLONE_UPLOAD" == "true" ] || { FATAL "RCLONE_UPLOAD is not equal to true.  Aborting."; exit 1; }
+
+# Check if the rclone config file is available and valid
+RCLONE_LOCAL=${RCLONE_LOCAL:="local"}
+RCLONE_CONFIG_FILE=${RCLONE_CONFIG_FILE:="/config/rclone.conf"}
+[ -f "$RCLONE_CONFIG_FILE" ] || { FATAL "I require "$RCLONE_CONFIG_FILE" but it cannot be found.  Aborting."; exit 1; }
+[ -z ${RCLONE_REMOTE+x} ] && { FATAL "I require environment variable RCLONE_REMOTE but it is not set.  Aborting."; exit 1; }
+# If the RCLONE_REMOTE does not contain : then add it
+RCLONE_REMOTE_HOST=`echo "$RCLONE_REMOTE" | cut -f1 -d':'`
+[ -z "${RCLONE_REMOTE##*:*}" ] && \
+  RCLONE_REMOTE_PATH=`echo "$RCLONE_REMOTE" | cut -f2 -d':'` || \
+  RCLONE_REMOTE_PATH=""
+
+crudini --get --existing=section "$RCLONE_CONFIG_FILE" | grep -q "$RCLONE_REMOTE_HOST" || { FATAL "Looks like rclone.conf does not contain the required [${RCLONE_REMOTE}] section.  Aborting."; exit 1; }
+crudini --get --existing=section "$RCLONE_CONFIG_FILE" | grep -q "$RCLONE_LOCAL" || { FATAL "Looks like rclone.conf does not contain the required [${RCLONE_LOCAL}] section.  Aborting."; exit 1; }
+
+# Check if we have the required variables
 FILENAME="$1"
+[ "$FILENAME" != "" ] || { FATAL "Empty filename passed.  Aborting."; exit 1; }
+[ -f "$FILENAME" ] || { FATAL "File "${FILENAME}" does not exist.  Aborting."; exit 1; }
+BASE_FILENAME=`basename "$FILENAME"`
 UPLOADED_FILENAME="$2"
+# If we have passed an UPLOADED_FILENAME then use that, otherwise get it from the file
+[ "$UPLOADED_FILENAME" == "" ] && UPLOADED_FILENAME="${BASE_FILENAME}"
+REMOTE="${RCLONE_REMOTE_HOST}:${RCLONE_REMOTE_PATH}/${UPLOADED_FILENAME}"
 
-if [ -z ${RCLONE_REMOTE+x} ]; then
-  echo "RCLONE_REMOTE variable is not set"
-  exit 1
-fi
+# I'm just using this for debugging
+# echo "rclone \
+# 	--config \"${RCLONE_CONFIG_FILE}\" \
+# 	copyto \
+#   \"${RCLONE_LOCAL}:${FILENAME}\" \
+# 	\"$REMOTE\""
 
-if [[ "${UPLOADED_FILENAME}" == "" ]]; then
-  BASE_FILENAME=`basename "$FILENAME"`
-  REMOTE="${RCLONE_REMOTE}/${BASE_FILENAME}"
-else
-  REMOTE="${RCLONE_REMOTE}/${UPLOADED_FILENAME}"
-fi
-
-if [[ ! -f "$FILENAME" ]]; then
-   echo "File does not exist!"
-   echo "$FILENAME"
-   exit 1
-fi
-
-if [[ ! -f "${RCLONE_CONFIG_FILE}" ]]; then
-   echo "rclone config file does not exist!"
-   echo "${RCLONE_CONFIG_FILE}"
-   exit 1
-fi
-
-rclone \
+# Check if we need to take any action
+# if we get FAIL then the file is different or missing
+FILE_CHECK=`rclone \
+  -q \
 	--config "${RCLONE_CONFIG_FILE}" \
-	copyto \
-	"${RCLONE_LOCAL}:${FILENAME}" \
-	"$REMOTE"
+  check \
+  "${RCLONE_LOCAL}:${FILENAME}" \
+  "${RCLONE_REMOTE_HOST}:${RCLONE_REMOTE_PATH}/" \
+  2>/dev/null && \
+    echo "OK" || \
+    echo "FAIL"`
+
+if [[ "$FILE_CHECK" == "FAIL" ]]; then
+  rclone \
+    --log-level "INFO" \
+    --stats-log-level "DEBUG" \
+    --log-file "${GOOGLE_DRIVE_UPLOAD_LOG_FILE}" \
+  	--config "${RCLONE_CONFIG_FILE}" \
+  	copyto \
+  	"${RCLONE_LOCAL}:${FILENAME}" \
+  	"$REMOTE"
+else
+    INFO "File '${RCLONE_REMOTE_PATH}/${UPLOADED_FILENAME}' Exists. Skipping Upload."
+fi
+
+exit 0
